trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  keyVaultName: "my-keyvault-name"
  certificateName: "my-certificate"

steps:
  # --- Install Tools ---
  - template: ../kubernetes-pipeline/templates/install-k8s-tools.yaml
    parameters:
      installAzureCLI: true
      shellType: 'bash'

  # --- Download secure files from Library ---
  - task: DownloadSecureFile@1
    name: pfxFile
    inputs:
      secureFile: "cert.pfx"           # <-- PFX certificate file in Library

  - task: DownloadSecureFile@1
    name: pfxPassword
    inputs:
      secureFile: "cert-password.txt"  # <-- Password file in Library

  # --- Import PFX certificate to Key Vault ---
  - task: AzureCLI@2
    displayName: "Import PFX certificate to Key Vault"
    inputs:
      azureSubscription: "My-Azure-Service-Connection"  # <-- your service connection name
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        # Read password from file
        PFX_PASSWORD=$(cat "$(pfxPassword.secureFilePath)")

        echo "Importing PFX certificate to Key Vault: $(certificateName)"
        az keyvault certificate import \
          --vault-name "$(keyVaultName)" \
          --name "$(certificateName)" \
          --file "$(pfxFile.secureFilePath)" \
          --password "$PFX_PASSWORD" \
          --output none

        echo "Certificate imported successfully"

